openapi: 3.1.0
x-stoplight:
  id: d2x4dncugtunk
info:
  title: Client Management API
  version: '1.0'
  summary: API that manages clients in Hermes SMS Gateway
  description: ''
  contact:
    name: Delfim Marime
    url: raitonbl.com
    email: delfimarime@outlook.com
servers:
  - url: 'http://localhost:3000'
paths:
  /clients:
    get:
      summary: Get Clients Page
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponsePage'
                  - type: object
                    x-stoplight:
                      id: n1h07ldzaahqw
                    properties:
                      items:
                        type: array
                        x-stoplight:
                          id: 2ckgyca2p2few
                        items:
                          x-stoplight:
                            id: a158s3wsei6on
                          type: object
      operationId: get-clients
      parameters:
        - $ref: ./smsc.management.yaml#/components/parameters/search
        - $ref: ./smsc.management.yaml#/components/parameters/page
        - $ref: ./smsc.management.yaml#/components/parameters/limit
        - schema:
            type: boolean
          in: query
          name: is_enabled
components:
  schemas:
    ResponsePage:
      type: object
      x-stoplight:
        id: 0kpcrc9g42ugr
      required:
        - next
        - prev
      properties:
        self:
          description: Pagination link|cursor pointing to the current page.
          type: string
          format: uri
        first:
          description: Pagination link|cursor pointing to the first page.
          type: string
          format: uri
        prev:
          description: Pagination link|cursor pointing to the previous page.
          type: string
          format: uri
        next:
          description: Pagination link|cursor pointing to the next page.
          type: string
          format: uri
        last:
          description: Pagination link|cursor pointing to the last page.
          type: string
          format: uri
    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: |
            A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-9457, it is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
          default: 'about:blank'
          example: /some/uri-reference
        title:
          type: string
          description: |
            A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
          example: some title for the error situation
        status:
          type: number
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
          example: some description for the error situation
        instance:
          type: string
          format: uri-reference
          description: |
            A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.
          example: /some/uri-reference#specific-occurrence-context
    PaginatedEvent:
      title: PaginatedEvent
      x-stoplight:
        id: 54o1g8rnbijh0
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: firi7mczm6od4
          format: uuid
        type:
          type: object
          x-stoplight:
            id: gtepv1clb1gd2
          properties:
            name:
              type: string
              x-stoplight:
                id: wc3bpd7cwh7fn
            audience:
              type: string
              x-stoplight:
                id: 8w7841hnb6gvv
        created_at:
          type: string
          x-stoplight:
            id: vb3kh7i1rt3cb
          format: date-time
        created_by:
          type: string
          x-stoplight:
            id: 4nqco5k95h1wg
          description: Username of the user who initiated it
        triggered_by:
          type: string
          x-stoplight:
            id: 8900qb58a738n
          description: The system used to initiate the event
      required:
        - id
        - type
        - created_at
        - triggered_by
    Event:
      title: Event
      x-stoplight:
        id: h6isufd5l43xn
      allOf:
        - $ref: '#/components/schemas/PaginatedEvent'
    PaginatedClient:
      title: PaginatedClient
      x-stoplight:
        id: ym4eddiktbn93
      type: object
      properties:
        id:
          type: string
          format: uuid
        client_id:
          type: string
          x-stoplight:
            id: fzzmhq1f633mn
        name:
          type: string
          x-stoplight:
            id: v68ps3l0asyth
        description:
          type: string
          x-stoplight:
            id: fipjp2h335gn8
        type:
          type: string
          x-stoplight:
            id: cxiuksmxfmzu3
          enum:
            - BACKEND
            - FRONTEND
        is_enabled:
          type: boolean
          x-stoplight:
            id: xdjc1d0cjtzxf
      required:
        - id
        - client_id
        - name
        - type
        - is_enabled
    Client:
      title: Client
      x-stoplight:
        id: 7rpal7rrs44wh
      allOf:
        - $ref: '#/components/schemas/PaginatedClient'
        - type: object
          x-stoplight:
            id: knt5n2jb83ofd
          properties:
            created_at:
              type: string
              x-stoplight:
                id: ba9y15zilxhfz
            created_by:
              type: string
              x-stoplight:
                id: 4k7axmuo65qe2
            managed_by:
              type: object
              x-stoplight:
                id: ubcu1i81ctn01
              additionalProperties: false
              required:
                - interface
                - name
              properties:
                interface:
                  type: string
                  x-stoplight:
                    id: dmd34q623sxoj
                  enum:
                    - SQS_CLIENT
                    - KAFKA_CLIENT
                    - RABBITMQ_CLIENT
                    - SNS_CLIENT
                name:
                  type: string
                  x-stoplight:
                    id: q27lfs8fyek5x
          required:
            - managed_by
    Callback:
      title: Callback
      x-stoplight:
        id: i68vyffy19j2j
      allOf:
        - description: HTTP Callback
          properties:
            url:
              type: string
              x-stoplight:
                id: apluild2878xc
            method:
              type: string
              x-stoplight:
                id: v0ngjfove86be
              enum:
                - GET
                - POST
                - PUT
                - PATCH
            request:
              type: object
              x-stoplight:
                id: koqox8tkz2t6k
              properties:
                body:
                  type: string
                  x-stoplight:
                    id: g6p6biv8o02jk
                headers:
                  type:
                    - object
                  x-stoplight:
                    id: b9yttrzvqowh3
                  additionalProperties: false
                  minProperties: 1
            security:
              x-stoplight:
                id: rcaxb192y4x9h
              allOf:
                - additionalProperties: false
                  properties:
                    type:
                      type: string
                      x-stoplight:
                        id: k2soz8vp1s4kk
                    username:
                      type: string
                      x-stoplight:
                        id: sd10zz5eqadit
                    password:
                      type: string
                      x-stoplight:
                        id: d1uytpm6vmyhl
                  required:
                    - type
                    - username
                    - password
                - x-stoplight:
                    id: xt3eyeg7zgz5v
                  properties:
                    type:
                      type: string
                      x-stoplight:
                        id: c9q61o9058qj2
                      enum:
                        - TOKEN
                    header:
                      type: string
                      x-stoplight:
                        id: gelw8lz7fmrqt
                      default: Authorization
                    token:
                      type: string
                      x-stoplight:
                        id: 1aq6bbgqnc69y
                  required:
                    - type
                    - header
                    - token
                - x-stoplight:
                    id: n8u8dxvo3tc27
                  properties:
                    type:
                      type: string
                      x-stoplight:
                        id: pq3jm91hm1md6
                    client_id:
                      type: string
                      x-stoplight:
                        id: 5dj88qdvggahb
                    client_secret:
                      type: string
                      x-stoplight:
                        id: 6ogjaprgzyrxh
                    token_url:
                      type: string
                      x-stoplight:
                        id: thrtc26jfj44p
                  required:
                    - type
                    - client_id
                    - client_secret
                    - token_url
              type: object
        - x-stoplight:
            id: hvlnop87n9qwk
          properties:
            queue:
              type: object
              x-stoplight:
                id: gqa1oi17gufik
              minProperties: 1
              maxProperties: 1
              properties:
                name:
                  type: string
                  x-stoplight:
                    id: y8bckfsfdbbll
                url:
                  type: string
                  x-stoplight:
                    id: ahdxs97p98bu1
            topic:
              type: object
              x-stoplight:
                id: 7ol97d3x8lchk
              properties:
                name:
                  type: string
                  x-stoplight:
                    id: fa9sh0qy2fpdl
              required:
                - name
            type:
              type: string
              x-stoplight:
                id: 6lpjj8g45soqh
              enum:
                - KAFKA_CLIENT
                - RABBITMQ_CLIENT
                - SQS_CLIENT
                - SNS_CLIENT
                
      type: object
  securitySchemes: {}
  parameters:
    search:
      name: s
      in: query
      required: false
      schema:
        type: string
      description: Search like
    page:
      name: page
      in: query
      required: false
      schema:
        type: number
        minimum: 1
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: number
        minimum: 10
        default: 15
  responses:
    Problem:
      description: '500'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
security:
  - OpenID Connect Provider: []
